### ISSUE TITLE
Actionbar borders?

### ISSUE THREAD

**Issue by trex54** [liquidbase/DuffedUIv8#73]
I just updated the UI, and now all the Actionbars have lost their borders, and the spacing looks super off because of it. It also seems everything shifted just a tiny bit. I had the Exorsus ready check bar in between the left chat and the main action bars, and now the action bars on the left side are cutting into it, something they've never done before.
![wowscrnshot_020718_135228](https://user-images.githubusercontent.com/36242270/35935362-3d7cf9a2-0c0e-11e8-8f3d-1ce7c4dd1101.jpg)

**Comment by liquidbase** [comment]
They are no problems. I've changed the positions of the XP and artifact bar, causing the sidebars to shift slightly inward. For you, the XP bar is currently still active, so the left sidebar is a little bit moved inwards. The panels on the action bars are no longer displayed because an option is activated, which is deactivated normally. The option is called "Hide panels on actionbars" and can be found under the section Actionbars in the config.
