### ISSUE TITLE
Legendary Leather Boots Buff

### ISSUE THREAD

**Issue by trex54** [liquidbase/DuffedUIv8#76]
Hey so I have the legendary leather boots that are craftable, that turn you into wisp after 5 kills, and my UI absolutely hates it. I have thousands of errors and my chat goes crazy telling me about all the errors. Not sure if this can be fixed. I included a screenshot of the buff and the error from buggrabber.
![wowscrnshot_021018_163158](https://user-images.githubusercontent.com/36242270/36066866-27b743ba-0e80-11e8-9f81-3bfd612899a3.jpg)

**Comment by liquidbase** [comment]
Take a look into it after I'm @home tomorrow.

**Comment by trex54** [comment]
Any update?

**Comment by liquidbase** [comment]
Yes there is.
So far I could not reproduce the issue with me, not even with different classes who wear the legendary boots. That's why I would like to ask you, if the bug should appear next time in your chat enter the following:
```
/dump UnitPower("player")
/dump UnitPowerMax("player")
```
It is important that you enter both commands when you have the buff of the boots. Please post the result in the comments.

**Comment by trex54** [comment]
![wowscrnshot_021518_022727](https://user-images.githubusercontent.com/36242270/36245163-cfd708a8-11f7-11e8-8d95-5b7ccc15daf6.jpg)
 Both values say [1]=0

**Comment by liquidbase** [comment]
Thanks vor the values.
Please check the latest commit here on github if the fix works correctly.
